day=input()
if(day=='Monday'):
  print('no')
elif(day=='Tuesday'):
  print('no')
elif(day=='Wednesday'):
  print('no')
elif(day=='Thusday'):
  print('no')
elif(day=='Friday'):
  print('no')
elif(day=='Saturday'):
  print('yes')
elif(day=='Sunday'):
  print('yes')
